// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-routing-api-poc/models"
	"github.com/ONSdigital/dis-routing-api-poc/store"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that StorerMock does implement store.Storer.
// If this is not the case, regenerate this file with moq.
var _ store.Storer = &StorerMock{}

// StorerMock is a mock implementation of store.Storer.
//
//	func TestSomethingThatUsesStorer(t *testing.T) {
//
//		// make and configure a mocked store.Storer
//		mockedStorer := &StorerMock{
//			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CloseFunc: func(ctx context.Context) error {
//				panic("mock out the Close method")
//			},
//			CreateRedirectFunc: func(ctx context.Context, redirect *models.Redirect) error {
//				panic("mock out the CreateRedirect method")
//			},
//			CreateRouteFunc: func(ctx context.Context, route *models.Route) error {
//				panic("mock out the CreateRoute method")
//			},
//			DeleteRedirectFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteRedirect method")
//			},
//			DeleteRouteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteRoute method")
//			},
//			GetAllRedirectsFunc: func(ctx context.Context, filter map[string]interface{}) (*[]models.Redirect, error) {
//				panic("mock out the GetAllRedirects method")
//			},
//			GetAllRoutesFunc: func(ctx context.Context, filter map[string]interface{}) (*[]models.Route, error) {
//				panic("mock out the GetAllRoutes method")
//			},
//			GetRedirectFunc: func(ctx context.Context, id string) (*models.Redirect, error) {
//				panic("mock out the GetRedirect method")
//			},
//			GetRouteFunc: func(ctx context.Context, id string) (*models.Route, error) {
//				panic("mock out the GetRoute method")
//			},
//			UpdateRedirectFunc: func(ctx context.Context, id string, update map[string]interface{}) error {
//				panic("mock out the UpdateRedirect method")
//			},
//			UpdateRouteFunc: func(ctx context.Context, id string, update map[string]interface{}) error {
//				panic("mock out the UpdateRoute method")
//			},
//			ValidateRedirectFunc: func(ctx context.Context, redirect *models.Redirect) error {
//				panic("mock out the ValidateRedirect method")
//			},
//			ValidateRouteFunc: func(ctx context.Context, route *models.Route) error {
//				panic("mock out the ValidateRoute method")
//			},
//		}
//
//		// use mockedStorer in code that requires store.Storer
//		// and then make assertions.
//
//	}
type StorerMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// CreateRedirectFunc mocks the CreateRedirect method.
	CreateRedirectFunc func(ctx context.Context, redirect *models.Redirect) error

	// CreateRouteFunc mocks the CreateRoute method.
	CreateRouteFunc func(ctx context.Context, route *models.Route) error

	// DeleteRedirectFunc mocks the DeleteRedirect method.
	DeleteRedirectFunc func(ctx context.Context, id string) error

	// DeleteRouteFunc mocks the DeleteRoute method.
	DeleteRouteFunc func(ctx context.Context, id string) error

	// GetAllRedirectsFunc mocks the GetAllRedirects method.
	GetAllRedirectsFunc func(ctx context.Context, filter map[string]interface{}) (*[]models.Redirect, error)

	// GetAllRoutesFunc mocks the GetAllRoutes method.
	GetAllRoutesFunc func(ctx context.Context, filter map[string]interface{}) (*[]models.Route, error)

	// GetRedirectFunc mocks the GetRedirect method.
	GetRedirectFunc func(ctx context.Context, id string) (*models.Redirect, error)

	// GetRouteFunc mocks the GetRoute method.
	GetRouteFunc func(ctx context.Context, id string) (*models.Route, error)

	// UpdateRedirectFunc mocks the UpdateRedirect method.
	UpdateRedirectFunc func(ctx context.Context, id string, update map[string]interface{}) error

	// UpdateRouteFunc mocks the UpdateRoute method.
	UpdateRouteFunc func(ctx context.Context, id string, update map[string]interface{}) error

	// ValidateRedirectFunc mocks the ValidateRedirect method.
	ValidateRedirectFunc func(ctx context.Context, redirect *models.Redirect) error

	// ValidateRouteFunc mocks the ValidateRoute method.
	ValidateRouteFunc func(ctx context.Context, route *models.Route) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateRedirect holds details about calls to the CreateRedirect method.
		CreateRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Redirect is the redirect argument value.
			Redirect *models.Redirect
		}
		// CreateRoute holds details about calls to the CreateRoute method.
		CreateRoute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Route is the route argument value.
			Route *models.Route
		}
		// DeleteRedirect holds details about calls to the DeleteRedirect method.
		DeleteRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// DeleteRoute holds details about calls to the DeleteRoute method.
		DeleteRoute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetAllRedirects holds details about calls to the GetAllRedirects method.
		GetAllRedirects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter map[string]interface{}
		}
		// GetAllRoutes holds details about calls to the GetAllRoutes method.
		GetAllRoutes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter map[string]interface{}
		}
		// GetRedirect holds details about calls to the GetRedirect method.
		GetRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetRoute holds details about calls to the GetRoute method.
		GetRoute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// UpdateRedirect holds details about calls to the UpdateRedirect method.
		UpdateRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Update is the update argument value.
			Update map[string]interface{}
		}
		// UpdateRoute holds details about calls to the UpdateRoute method.
		UpdateRoute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Update is the update argument value.
			Update map[string]interface{}
		}
		// ValidateRedirect holds details about calls to the ValidateRedirect method.
		ValidateRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Redirect is the redirect argument value.
			Redirect *models.Redirect
		}
		// ValidateRoute holds details about calls to the ValidateRoute method.
		ValidateRoute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Route is the route argument value.
			Route *models.Route
		}
	}
	lockChecker          sync.RWMutex
	lockClose            sync.RWMutex
	lockCreateRedirect   sync.RWMutex
	lockCreateRoute      sync.RWMutex
	lockDeleteRedirect   sync.RWMutex
	lockDeleteRoute      sync.RWMutex
	lockGetAllRedirects  sync.RWMutex
	lockGetAllRoutes     sync.RWMutex
	lockGetRedirect      sync.RWMutex
	lockGetRoute         sync.RWMutex
	lockUpdateRedirect   sync.RWMutex
	lockUpdateRoute      sync.RWMutex
	lockValidateRedirect sync.RWMutex
	lockValidateRoute    sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *StorerMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("StorerMock.CheckerFunc: method is nil but Storer.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedStorer.CheckerCalls())
func (mock *StorerMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *StorerMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("StorerMock.CloseFunc: method is nil but Storer.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStorer.CloseCalls())
func (mock *StorerMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CreateRedirect calls CreateRedirectFunc.
func (mock *StorerMock) CreateRedirect(ctx context.Context, redirect *models.Redirect) error {
	if mock.CreateRedirectFunc == nil {
		panic("StorerMock.CreateRedirectFunc: method is nil but Storer.CreateRedirect was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Redirect *models.Redirect
	}{
		Ctx:      ctx,
		Redirect: redirect,
	}
	mock.lockCreateRedirect.Lock()
	mock.calls.CreateRedirect = append(mock.calls.CreateRedirect, callInfo)
	mock.lockCreateRedirect.Unlock()
	return mock.CreateRedirectFunc(ctx, redirect)
}

// CreateRedirectCalls gets all the calls that were made to CreateRedirect.
// Check the length with:
//
//	len(mockedStorer.CreateRedirectCalls())
func (mock *StorerMock) CreateRedirectCalls() []struct {
	Ctx      context.Context
	Redirect *models.Redirect
} {
	var calls []struct {
		Ctx      context.Context
		Redirect *models.Redirect
	}
	mock.lockCreateRedirect.RLock()
	calls = mock.calls.CreateRedirect
	mock.lockCreateRedirect.RUnlock()
	return calls
}

// CreateRoute calls CreateRouteFunc.
func (mock *StorerMock) CreateRoute(ctx context.Context, route *models.Route) error {
	if mock.CreateRouteFunc == nil {
		panic("StorerMock.CreateRouteFunc: method is nil but Storer.CreateRoute was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Route *models.Route
	}{
		Ctx:   ctx,
		Route: route,
	}
	mock.lockCreateRoute.Lock()
	mock.calls.CreateRoute = append(mock.calls.CreateRoute, callInfo)
	mock.lockCreateRoute.Unlock()
	return mock.CreateRouteFunc(ctx, route)
}

// CreateRouteCalls gets all the calls that were made to CreateRoute.
// Check the length with:
//
//	len(mockedStorer.CreateRouteCalls())
func (mock *StorerMock) CreateRouteCalls() []struct {
	Ctx   context.Context
	Route *models.Route
} {
	var calls []struct {
		Ctx   context.Context
		Route *models.Route
	}
	mock.lockCreateRoute.RLock()
	calls = mock.calls.CreateRoute
	mock.lockCreateRoute.RUnlock()
	return calls
}

// DeleteRedirect calls DeleteRedirectFunc.
func (mock *StorerMock) DeleteRedirect(ctx context.Context, id string) error {
	if mock.DeleteRedirectFunc == nil {
		panic("StorerMock.DeleteRedirectFunc: method is nil but Storer.DeleteRedirect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRedirect.Lock()
	mock.calls.DeleteRedirect = append(mock.calls.DeleteRedirect, callInfo)
	mock.lockDeleteRedirect.Unlock()
	return mock.DeleteRedirectFunc(ctx, id)
}

// DeleteRedirectCalls gets all the calls that were made to DeleteRedirect.
// Check the length with:
//
//	len(mockedStorer.DeleteRedirectCalls())
func (mock *StorerMock) DeleteRedirectCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteRedirect.RLock()
	calls = mock.calls.DeleteRedirect
	mock.lockDeleteRedirect.RUnlock()
	return calls
}

// DeleteRoute calls DeleteRouteFunc.
func (mock *StorerMock) DeleteRoute(ctx context.Context, id string) error {
	if mock.DeleteRouteFunc == nil {
		panic("StorerMock.DeleteRouteFunc: method is nil but Storer.DeleteRoute was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRoute.Lock()
	mock.calls.DeleteRoute = append(mock.calls.DeleteRoute, callInfo)
	mock.lockDeleteRoute.Unlock()
	return mock.DeleteRouteFunc(ctx, id)
}

// DeleteRouteCalls gets all the calls that were made to DeleteRoute.
// Check the length with:
//
//	len(mockedStorer.DeleteRouteCalls())
func (mock *StorerMock) DeleteRouteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteRoute.RLock()
	calls = mock.calls.DeleteRoute
	mock.lockDeleteRoute.RUnlock()
	return calls
}

// GetAllRedirects calls GetAllRedirectsFunc.
func (mock *StorerMock) GetAllRedirects(ctx context.Context, filter map[string]interface{}) (*[]models.Redirect, error) {
	if mock.GetAllRedirectsFunc == nil {
		panic("StorerMock.GetAllRedirectsFunc: method is nil but Storer.GetAllRedirects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter map[string]interface{}
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllRedirects.Lock()
	mock.calls.GetAllRedirects = append(mock.calls.GetAllRedirects, callInfo)
	mock.lockGetAllRedirects.Unlock()
	return mock.GetAllRedirectsFunc(ctx, filter)
}

// GetAllRedirectsCalls gets all the calls that were made to GetAllRedirects.
// Check the length with:
//
//	len(mockedStorer.GetAllRedirectsCalls())
func (mock *StorerMock) GetAllRedirectsCalls() []struct {
	Ctx    context.Context
	Filter map[string]interface{}
} {
	var calls []struct {
		Ctx    context.Context
		Filter map[string]interface{}
	}
	mock.lockGetAllRedirects.RLock()
	calls = mock.calls.GetAllRedirects
	mock.lockGetAllRedirects.RUnlock()
	return calls
}

// GetAllRoutes calls GetAllRoutesFunc.
func (mock *StorerMock) GetAllRoutes(ctx context.Context, filter map[string]interface{}) (*[]models.Route, error) {
	if mock.GetAllRoutesFunc == nil {
		panic("StorerMock.GetAllRoutesFunc: method is nil but Storer.GetAllRoutes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter map[string]interface{}
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllRoutes.Lock()
	mock.calls.GetAllRoutes = append(mock.calls.GetAllRoutes, callInfo)
	mock.lockGetAllRoutes.Unlock()
	return mock.GetAllRoutesFunc(ctx, filter)
}

// GetAllRoutesCalls gets all the calls that were made to GetAllRoutes.
// Check the length with:
//
//	len(mockedStorer.GetAllRoutesCalls())
func (mock *StorerMock) GetAllRoutesCalls() []struct {
	Ctx    context.Context
	Filter map[string]interface{}
} {
	var calls []struct {
		Ctx    context.Context
		Filter map[string]interface{}
	}
	mock.lockGetAllRoutes.RLock()
	calls = mock.calls.GetAllRoutes
	mock.lockGetAllRoutes.RUnlock()
	return calls
}

// GetRedirect calls GetRedirectFunc.
func (mock *StorerMock) GetRedirect(ctx context.Context, id string) (*models.Redirect, error) {
	if mock.GetRedirectFunc == nil {
		panic("StorerMock.GetRedirectFunc: method is nil but Storer.GetRedirect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRedirect.Lock()
	mock.calls.GetRedirect = append(mock.calls.GetRedirect, callInfo)
	mock.lockGetRedirect.Unlock()
	return mock.GetRedirectFunc(ctx, id)
}

// GetRedirectCalls gets all the calls that were made to GetRedirect.
// Check the length with:
//
//	len(mockedStorer.GetRedirectCalls())
func (mock *StorerMock) GetRedirectCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetRedirect.RLock()
	calls = mock.calls.GetRedirect
	mock.lockGetRedirect.RUnlock()
	return calls
}

// GetRoute calls GetRouteFunc.
func (mock *StorerMock) GetRoute(ctx context.Context, id string) (*models.Route, error) {
	if mock.GetRouteFunc == nil {
		panic("StorerMock.GetRouteFunc: method is nil but Storer.GetRoute was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRoute.Lock()
	mock.calls.GetRoute = append(mock.calls.GetRoute, callInfo)
	mock.lockGetRoute.Unlock()
	return mock.GetRouteFunc(ctx, id)
}

// GetRouteCalls gets all the calls that were made to GetRoute.
// Check the length with:
//
//	len(mockedStorer.GetRouteCalls())
func (mock *StorerMock) GetRouteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetRoute.RLock()
	calls = mock.calls.GetRoute
	mock.lockGetRoute.RUnlock()
	return calls
}

// UpdateRedirect calls UpdateRedirectFunc.
func (mock *StorerMock) UpdateRedirect(ctx context.Context, id string, update map[string]interface{}) error {
	if mock.UpdateRedirectFunc == nil {
		panic("StorerMock.UpdateRedirectFunc: method is nil but Storer.UpdateRedirect was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Update map[string]interface{}
	}{
		Ctx:    ctx,
		ID:     id,
		Update: update,
	}
	mock.lockUpdateRedirect.Lock()
	mock.calls.UpdateRedirect = append(mock.calls.UpdateRedirect, callInfo)
	mock.lockUpdateRedirect.Unlock()
	return mock.UpdateRedirectFunc(ctx, id, update)
}

// UpdateRedirectCalls gets all the calls that were made to UpdateRedirect.
// Check the length with:
//
//	len(mockedStorer.UpdateRedirectCalls())
func (mock *StorerMock) UpdateRedirectCalls() []struct {
	Ctx    context.Context
	ID     string
	Update map[string]interface{}
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Update map[string]interface{}
	}
	mock.lockUpdateRedirect.RLock()
	calls = mock.calls.UpdateRedirect
	mock.lockUpdateRedirect.RUnlock()
	return calls
}

// UpdateRoute calls UpdateRouteFunc.
func (mock *StorerMock) UpdateRoute(ctx context.Context, id string, update map[string]interface{}) error {
	if mock.UpdateRouteFunc == nil {
		panic("StorerMock.UpdateRouteFunc: method is nil but Storer.UpdateRoute was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Update map[string]interface{}
	}{
		Ctx:    ctx,
		ID:     id,
		Update: update,
	}
	mock.lockUpdateRoute.Lock()
	mock.calls.UpdateRoute = append(mock.calls.UpdateRoute, callInfo)
	mock.lockUpdateRoute.Unlock()
	return mock.UpdateRouteFunc(ctx, id, update)
}

// UpdateRouteCalls gets all the calls that were made to UpdateRoute.
// Check the length with:
//
//	len(mockedStorer.UpdateRouteCalls())
func (mock *StorerMock) UpdateRouteCalls() []struct {
	Ctx    context.Context
	ID     string
	Update map[string]interface{}
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Update map[string]interface{}
	}
	mock.lockUpdateRoute.RLock()
	calls = mock.calls.UpdateRoute
	mock.lockUpdateRoute.RUnlock()
	return calls
}

// ValidateRedirect calls ValidateRedirectFunc.
func (mock *StorerMock) ValidateRedirect(ctx context.Context, redirect *models.Redirect) error {
	if mock.ValidateRedirectFunc == nil {
		panic("StorerMock.ValidateRedirectFunc: method is nil but Storer.ValidateRedirect was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Redirect *models.Redirect
	}{
		Ctx:      ctx,
		Redirect: redirect,
	}
	mock.lockValidateRedirect.Lock()
	mock.calls.ValidateRedirect = append(mock.calls.ValidateRedirect, callInfo)
	mock.lockValidateRedirect.Unlock()
	return mock.ValidateRedirectFunc(ctx, redirect)
}

// ValidateRedirectCalls gets all the calls that were made to ValidateRedirect.
// Check the length with:
//
//	len(mockedStorer.ValidateRedirectCalls())
func (mock *StorerMock) ValidateRedirectCalls() []struct {
	Ctx      context.Context
	Redirect *models.Redirect
} {
	var calls []struct {
		Ctx      context.Context
		Redirect *models.Redirect
	}
	mock.lockValidateRedirect.RLock()
	calls = mock.calls.ValidateRedirect
	mock.lockValidateRedirect.RUnlock()
	return calls
}

// ValidateRoute calls ValidateRouteFunc.
func (mock *StorerMock) ValidateRoute(ctx context.Context, route *models.Route) error {
	if mock.ValidateRouteFunc == nil {
		panic("StorerMock.ValidateRouteFunc: method is nil but Storer.ValidateRoute was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Route *models.Route
	}{
		Ctx:   ctx,
		Route: route,
	}
	mock.lockValidateRoute.Lock()
	mock.calls.ValidateRoute = append(mock.calls.ValidateRoute, callInfo)
	mock.lockValidateRoute.Unlock()
	return mock.ValidateRouteFunc(ctx, route)
}

// ValidateRouteCalls gets all the calls that were made to ValidateRoute.
// Check the length with:
//
//	len(mockedStorer.ValidateRouteCalls())
func (mock *StorerMock) ValidateRouteCalls() []struct {
	Ctx   context.Context
	Route *models.Route
} {
	var calls []struct {
		Ctx   context.Context
		Route *models.Route
	}
	mock.lockValidateRoute.RLock()
	calls = mock.calls.ValidateRoute
	mock.lockValidateRoute.RUnlock()
	return calls
}
